name: smart_vision
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.3+10

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hexcolor: ^3.0.1
  shared_preferences: ^2.2.3
  connectivity_plus: ^6.1.0
  http: ^1.2.2
  http_parser: ^4.0.2
  fl_chart: ^0.69.0
  flutter_bloc: ^8.1.6
  geolocator: ^12.0.0
  url_launcher: ^6.3.0
  flutter_native_splash: ^2.4.0
  dashed_circular_progress_bar: ^0.0.6
  firebase_core: ^3.4.0
  firebase_messaging: ^15.1.0
  flutter_local_notifications: ^18.0.1
  flutter_html: ^3.0.0
  path_provider: ^2.1.5
  shorebird_code_push: ^1.1.6
  intl: ^0.19.0
  image_picker: ^1.0.7
  device_info_plus: ^10.0.1
  upgrader: ^12.1.0
  package_info_plus: ^8.1.1
  new_version_plus: ^0.0.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.4.0

flutter_native_splash:
  android: true
  ios: true
  fullscreen: true

  # Light mode settings
  background_image: assets/images/splash_background.png
  
  # Dark mode settings
  background_image_dark: assets/images/splash_background.png

  # Ensure full-screen fit
  android_gravity: fill
  ios_content_mode: scaleAspectFill

  # Android 12-specific settings
  android_12:
    background_image: assets/images/splash_background.png
    background_image_dark: assets/images/splash_background.png

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - shorebird.yaml
    
  fonts:
    - family: Colfax
      fonts:
        - asset: assets/fonts/colfax/Colfax-Regular.otf
        - asset: assets/fonts/colfax/Colfax-Bold.otf
    - family: Arial
      fonts:
        - asset: assets/fonts/ARLRDBD.ttf